tunnel: 4da8c59f-5011-4fa7-aaff-3c7c72c68f80
credentials-file: /Users/tarttphd/.cloudflared/4da8c59f-5011-4fa7-aaff-3c7c72c68f80.json

ingress:
  - hostname: n8n.feelingsunplugged.space
    service: http://localhost:5678
  - service: http_status:404
